# Server porti
server.port=8001
# Database sozlamalari
spring.jpa.hibernate.ddl-auto=update
# Fayl hajmi limiti (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# src/main/resources/application.properties ichiga:
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
gemini.api.key=${GEMINI_API_KEY}